use serde::Serialize;
use std::fs;
use std::future::Future;
use std::io::Write;
use std::path::{Path, PathBuf};
use std::sync::Mutex;
use std::time::{Duration, SystemTime, UNIX_EPOCH};
use tokio::sync::Mutex as AsyncMutex;
use tracing::{info, warn};

use super::agent_config::AgentConfig;
use super::flight::{Flight, Issue, FlightApprovalRequest};
use super::orchestrator::OrchestratorSettings;
use super::shared::home_dir;
use super::workspace::Workspace;

/// A post-flight retrospective capturing what worked, what failed, and lessons learned.
/// Generated by AI after a flight completes, used to improve future flight planning.
#[derive(Debug, Clone, Serialize, serde::Deserialize)]
pub struct FlightRetrospective {
    pub id: String,
    pub flight_id: String,
    pub flight_title: String,
    pub summary: String,
    #[serde(default)]
    pub what_worked: Vec<String>,
    #[serde(default)]
    pub what_failed: Vec<String>,
    #[serde(default)]
    pub lessons_learned: Vec<String>,
    #[serde(default)]
    pub suggested_improvements: Vec<String>,
    #[serde(default)]
    pub tags: Vec<String>,
    pub created_at: u64,
}

/// A saved SSH server connection configuration.
#[derive(Debug, Clone, Serialize, serde::Deserialize)]
pub struct ServerConfig {
    pub id: String,
    pub name: String,
    pub host: String,
    #[serde(default = "default_ssh_port")]
    pub port: u16,
    pub username: String,
    pub auth_method: String, // "agent" | "key" | "password"
    #[serde(default)]
    pub key_path: Option<String>,
    #[serde(default)]
    pub remote_path: Option<String>,
    #[serde(default)]
    pub last_connected_at: Option<u64>,
    #[serde(default)]
    pub installed_agents: Vec<String>,
    /// SHA256 fingerprint of the host key captured at first-connect.
    /// `None` for legacy entries — those connect via TOFU fallback until
    /// the user re-saves the server to pin the key.
    #[serde(default)]
    pub host_fingerprint: Option<String>,
}

fn default_ssh_port() -> u16 {
    22
}

pub const STATE_FILENAME: &str = "state.v1.json";
const PROVIDER_SETTINGS_FILENAME: &str = "provider-settings.v1.json";
pub const DEFAULT_OLLAMA_ROOT_BASE_URL: &str = "http://localhost:11434";

static STATE_LOCK: Mutex<()> = Mutex::new(());
static PROVIDER_SETTINGS_LOCK: Mutex<()> = Mutex::new(());

/// Async-safe critical-section mutex for every state writer. Async callers
/// hold it across the **entire** load → mutate → save sequence, and sync
/// slice writers acquire it through a small blocking adapter before taking
/// `STATE_LOCK`. This gives async and sync writers one shared ordering, so
/// a stale async full-state save cannot overwrite a sync slice save that
/// landed between the async load and save.
///
/// Migration note: callers that take `&mut PersistedState` and only need
/// to be serialized against other planner-tool callers should use
/// [`with_state_lock`]. Sync state writers in this module must acquire this
/// gate before `STATE_LOCK`; do not invert that order.
static ASYNC_STATE_LOCK: AsyncMutex<()> = AsyncMutex::const_new(());

#[derive(Debug, Clone, Serialize, serde::Deserialize, Default)]
struct ProviderRuntimeSettings {
    #[serde(default)]
    ollama_base_url: Option<String>,
}

#[derive(Debug, Clone, Serialize, serde::Deserialize, Default)]
pub struct PersistedUiState {
    pub selected_flight_id: Option<String>,
    pub selected_view: Option<String>,
    pub theme: Option<String>,
}

#[derive(Debug, Clone, Serialize, serde::Deserialize)]
pub struct PersistedState {
    pub version: u32,
    pub flights: Vec<Flight>,
    pub agents: Vec<AgentConfig>,
    pub settings: OrchestratorSettings,
    pub ui: PersistedUiState,
    #[serde(default)]
    pub issues: Vec<Issue>,
    #[serde(default)]
    pub workspaces: Vec<Workspace>,
    #[serde(default)]
    pub retrospectives: Vec<FlightRetrospective>,
    #[serde(default)]
    pub memory_events: Vec<serde_json::Value>,
    #[serde(default)]
    pub memory_patterns: Vec<serde_json::Value>,
    #[serde(default)]
    pub servers: Vec<ServerConfig>,
    /// Flight Planner: pending / resolved `request_user_approval`
    /// records. Filed async-style by the planner via the MCP tool
    /// surface (E2) and drained by `resolve_flight_approval`.
    #[serde(default)]
    pub flight_approvals: Vec<FlightApprovalRequest>,
}

impl Default for PersistedState {
    fn default() -> Self {
        Self {
            version: 1,
            flights: Vec::new(),
            agents: Vec::new(),
            settings: OrchestratorSettings::default(),
            ui: PersistedUiState::default(),
            issues: Vec::new(),
            workspaces: Vec::new(),
            retrospectives: Vec::new(),
            memory_events: Vec::new(),
            memory_patterns: Vec::new(),
            servers: Vec::new(),
            flight_approvals: Vec::new(),
        }
    }
}

/// Get the PacketADE data directory (~/.packetade/).
///
/// Resolves the SAME directory for both reads and writes so a failed startup
/// migration can't strand the user on an empty new dir while their data sits
/// in the legacy dir:
/// - prefer the new dir if it already exists,
/// - otherwise fall back to the legacy dir if it exists,
/// - otherwise return the new dir (fresh install).
pub fn data_dir() -> PathBuf {
    let home = home_dir().unwrap_or_else(|| ".".to_string());
    let new_dir = PathBuf::from(&home).join(crate::core::brand::DATA_DIR_NAME);
    if new_dir.exists() {
        return new_dir;
    }
    let legacy_dir = PathBuf::from(&home).join(crate::core::brand::LEGACY_DATA_DIR_NAME);
    if legacy_dir.exists() {
        return legacy_dir;
    }
    new_dir
}

/// Ensure the data directory exists.
pub fn ensure_data_dir() -> Result<PathBuf, String> {
    let dir = data_dir();
    if !dir.exists() {
        fs::create_dir_all(&dir)
            .map_err(|e| format!("Failed to create data dir {:?}: {}", dir, e))?;
        info!(
            "Created {} data dir: {:?}",
            crate::core::brand::APP_NAME,
            dir
        );
    }
    Ok(dir)
}

/// Derive the sibling `.bak` path for a primary file, matching the exact
/// extension-mangling that `write_with_backup` uses (`<ext>.bak`).
fn backup_path_for(path: &Path) -> PathBuf {
    path.with_extension(format!(
        "{}.bak",
        path.extension()
            .and_then(|ext| ext.to_str())
            .unwrap_or("json")
    ))
}

/// Derive the sibling `.tmp` path for a primary file, matching the exact
/// extension-mangling that `write_with_backup` uses (`<ext>.tmp`). A `.tmp`
/// may survive on disk if a crash hit between the fsync and the rename-in.
fn tmp_path_for(path: &Path) -> PathBuf {
    path.with_extension(format!(
        "{}.tmp",
        path.extension()
            .and_then(|ext| ext.to_str())
            .unwrap_or("json")
    ))
}

/// Quarantine a corrupt primary file by renaming it out of the way BEFORE any
/// recovery or save runs. This is mandatory: if the corrupt primary stays in
/// place, the next `write_with_backup` would copy it into `.bak` and destroy
/// the last good backup. After a successful rename `path.exists()` is false,
/// so the backup step is skipped and the good `.bak` survives. Best-effort:
/// on failure (e.g. a Windows sharing violation) we warn and continue rather
/// than panic or block startup, mirroring the migration warn-and-continue style.
fn quarantine_corrupt(path: &Path) {
    let ts = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map(|d| d.as_secs())
        .unwrap_or(0);
    let quarantine = path.with_extension(format!(
        "{}.corrupt-{}",
        path.extension()
            .and_then(|ext| ext.to_str())
            .unwrap_or("json"),
        ts
    ));
    match fs::rename(path, &quarantine) {
        Ok(()) => warn!(
            "Quarantined corrupt {:?} -> {:?}; attempting recovery",
            path, quarantine
        ),
        Err(e) => warn!(
            "Failed to quarantine corrupt {:?}: {} — continuing recovery",
            path, e
        ),
    }
}

/// Read + parse a sibling file (`.bak` or `.tmp`) as `T`. Returns `Some` only
/// on a clean parse; any read or parse error yields `None` (the ladder simply
/// falls through to the next candidate).
fn try_recover<T: serde::de::DeserializeOwned>(path: &Path) -> Option<T> {
    let content = fs::read_to_string(path).ok()?;
    serde_json::from_str::<T>(&content).ok()
}

pub fn load_state() -> PersistedState {
    load_state_from(&data_dir())
}

/// Recovery ladder over a specific data directory. `load_state` is a thin
/// wrapper that resolves `data_dir()` and delegates here; splitting the
/// directory out keeps the ladder testable with an injected tempdir without
/// changing any runtime behavior.
fn load_state_from(dir: &Path) -> PersistedState {
    let path = dir.join(STATE_FILENAME);

    // 1. Primary: clean read+parse wins immediately.
    match fs::read_to_string(&path) {
        Ok(content) => match serde_json::from_str::<PersistedState>(&content) {
            Ok(state) => return state,
            Err(e) => {
                // 2. Primary parsed-but-corrupt: quarantine FIRST (before any
                // recovery/return) so the next save can't clobber the good .bak.
                warn!("Failed to parse {:?}: {}, attempting recovery", path, e);
                quarantine_corrupt(&path);
            }
        },
        Err(_) => {
            // File-missing: fall through to .bak/.tmp. Genuine first run (no
            // primary, no .bak, no .tmp) stays fast and silent → default.
        }
    }

    // Recovery is intentionally READ-ONLY. `load_state` is called from many
    // sites that do NOT hold STATE_LOCK (get_state, git, flight_attempts,
    // orchestration, worktree, …); re-persisting here would issue an unlocked
    // `write_with_backup` that can race a locked writer on the shared `.tmp`
    // and land a stale snapshot over fresh state — a lost update. We return the
    // recovered value and let the next lock-held save reconcile the primary
    // (the locked writer's own internal `load_state` returns the same recovered
    // value and writes it back properly under STATE_LOCK).

    // 3. Backup sibling (.bak).
    let backup_path = backup_path_for(&path);
    if let Some(state) = try_recover::<PersistedState>(&backup_path) {
        warn!("Recovered state from backup {:?}", backup_path);
        return state;
    }

    // 4. Orphaned tmp (.tmp) — a complete fsynced write that never renamed in.
    let tmp_path = tmp_path_for(&path);
    if let Some(state) = try_recover::<PersistedState>(&tmp_path) {
        warn!("Recovered state from orphaned tmp {:?}", tmp_path);
        return state;
    }

    // 5. Nothing recoverable → default.
    PersistedState::default()
}

fn save_state_inner(state: &PersistedState) -> Result<(), String> {
    let dir = ensure_data_dir()?;
    let path = dir.join(STATE_FILENAME);
    let json = serde_json::to_string_pretty(state)
        .map_err(|e| format!("Failed to serialize persisted state: {}", e))?;
    write_with_backup(&path, &json)?;
    Ok(())
}

fn lock_state_gate_blocking() -> tokio::sync::MutexGuard<'static, ()> {
    loop {
        if let Ok(guard) = ASYNC_STATE_LOCK.try_lock() {
            return guard;
        }
        std::thread::sleep(Duration::from_millis(1));
    }
}

pub fn save_state(state: &PersistedState) -> Result<(), String> {
    let _async_lock = lock_state_gate_blocking();
    let _lock = STATE_LOCK
        .lock()
        .map_err(|e| format!("Lock poisoned: {}", e))?;
    let mut state = state.clone();
    state.version += 1;
    save_state_inner(&state)
}

/// Atomic load → mutate → save under `STATE_LOCK`. Mirrors the slice-writer
/// pattern (e.g. `save_flights`) for callers that need to merge multiple
/// fields into the persisted state in a single critical section, instead of
/// `load_state(); mutate; save_state()` — which exposes a lost-update race
/// against concurrent slice writers landing between the load and the save.
pub fn update_state<F, R>(mutate: F) -> Result<R, String>
where
    F: FnOnce(&mut PersistedState) -> R,
{
    let _async_lock = lock_state_gate_blocking();
    let _lock = STATE_LOCK
        .lock()
        .map_err(|e| format!("Lock poisoned: {}", e))?;
    let mut state = load_state();
    let result = mutate(&mut state);
    state.version += 1;
    save_state_inner(&state)?;
    Ok(result)
}

/// Run an async closure with an exclusive load → mutate → save critical
/// section over `PersistedState`. Solves the lost-update race that
/// `load_state(); mutate; save_state()` exposes when called from
/// concurrent async contexts (e.g. multiple Flight Planner MCP tool
/// handlers firing in parallel within a single planner turn).
///
/// Contract:
///   * The closure receives a `&mut PersistedState` already loaded under
///     the mutex.
///   * If the closure returns `Ok(R)`, the state is persisted under the
///     same lock and `R` is returned to the caller.
///   * If the closure returns `Err`, the state is **not** persisted — the
///     mutex is released and the error is propagated unchanged.
///   * The mutex is held across the closure's `.await` points, so callers
///     MUST NOT re-enter `with_state_lock` from within their closure
///     (doing so will deadlock).
///   * Tokio `Mutex` is fair-ish and not cancellation-safe at the lock
///     acquire site — callers that need to abort should drop the future
///     *before* it acquires the lock.
///
/// Sync state writers in this module acquire the same gate before taking
/// `STATE_LOCK`, so this helper is serialized against both async planner
/// writers and sync slice writers.
pub async fn with_state_lock<F, Fut, R>(action: F) -> Result<R, String>
where
    F: FnOnce(&mut PersistedState) -> Fut,
    Fut: Future<Output = Result<R, String>>,
{
    let _guard = ASYNC_STATE_LOCK.lock().await;
    let mut state = load_state();
    let result = action(&mut state).await?;
    let _lock = STATE_LOCK
        .lock()
        .map_err(|e| format!("Lock poisoned: {}", e))?;
    state.version += 1;
    save_state_inner(&state)?;
    Ok(result)
}

pub fn save_flights(flights: Vec<Flight>) -> Result<(), String> {
    let _async_lock = lock_state_gate_blocking();
    let _lock = STATE_LOCK
        .lock()
        .map_err(|e| format!("Lock poisoned: {}", e))?;
    let mut state = load_state();
    state.flights = flights;
    state.version += 1;
    save_state_inner(&state)
}

pub fn save_agents(agents: Vec<AgentConfig>) -> Result<(), String> {
    let _async_lock = lock_state_gate_blocking();
    let _lock = STATE_LOCK
        .lock()
        .map_err(|e| format!("Lock poisoned: {}", e))?;
    let mut state = load_state();
    state.agents = agents;
    state.version += 1;
    save_state_inner(&state)
}

pub fn save_settings(settings: OrchestratorSettings) -> Result<(), String> {
    let _async_lock = lock_state_gate_blocking();
    let _lock = STATE_LOCK
        .lock()
        .map_err(|e| format!("Lock poisoned: {}", e))?;
    let mut state = load_state();
    state.settings = settings;
    state.version += 1;
    save_state_inner(&state)
}

pub fn save_ui(ui: PersistedUiState) -> Result<(), String> {
    let _async_lock = lock_state_gate_blocking();
    let _lock = STATE_LOCK
        .lock()
        .map_err(|e| format!("Lock poisoned: {}", e))?;
    let mut state = load_state();
    if let Some(value) = ui.selected_flight_id {
        state.ui.selected_flight_id = if value.is_empty() { None } else { Some(value) };
    }
    if let Some(value) = ui.selected_view {
        state.ui.selected_view = if value.is_empty() { None } else { Some(value) };
    }
    if let Some(value) = ui.theme {
        state.ui.theme = if value.is_empty() { None } else { Some(value) };
    }
    state.version += 1;
    save_state_inner(&state)
}

pub fn save_issues(issues: Vec<Issue>) -> Result<(), String> {
    let _async_lock = lock_state_gate_blocking();
    let _lock = STATE_LOCK
        .lock()
        .map_err(|e| format!("Lock poisoned: {}", e))?;
    let mut state = load_state();
    state.issues = issues;
    state.version += 1;
    save_state_inner(&state)
}

pub fn save_workspaces(workspaces: Vec<Workspace>) -> Result<(), String> {
    let _async_lock = lock_state_gate_blocking();
    let _lock = STATE_LOCK
        .lock()
        .map_err(|e| format!("Lock poisoned: {}", e))?;
    let mut state = load_state();
    state.workspaces = workspaces;
    state.version += 1;
    save_state_inner(&state)
}

pub fn save_servers(servers: Vec<ServerConfig>) -> Result<(), String> {
    let _async_lock = lock_state_gate_blocking();
    let _lock = STATE_LOCK
        .lock()
        .map_err(|e| format!("Lock poisoned: {}", e))?;
    let mut state = load_state();
    state.servers = servers;
    state.version += 1;
    save_state_inner(&state)
}

pub fn save_memory(
    events: Vec<serde_json::Value>,
    patterns: Vec<serde_json::Value>,
) -> Result<(), String> {
    let _async_lock = lock_state_gate_blocking();
    let _lock = STATE_LOCK
        .lock()
        .map_err(|e| format!("Lock poisoned: {}", e))?;
    let mut state = load_state();
    state.memory_events = events;
    state.memory_patterns = patterns;
    state.version += 1;
    save_state_inner(&state)
}

/// v0.8-H: atomically flip the `pinned` flag on a single LearnedPattern by id.
/// Returns the new `pinned` value (or `None` if the pattern was not found).
/// Storing as `serde_json::Value` lets us mutate the field in-place rather
/// than round-tripping the whole slice — robust across schema additions.
pub fn toggle_pinned_pattern(pattern_id: &str) -> Result<Option<bool>, String> {
    let _async_lock = lock_state_gate_blocking();
    let _lock = STATE_LOCK
        .lock()
        .map_err(|e| format!("Lock poisoned: {}", e))?;
    let mut state = load_state();
    let mut found: Option<bool> = None;
    for entry in state.memory_patterns.iter_mut() {
        let Some(obj) = entry.as_object_mut() else {
            continue;
        };
        let Some(id_val) = obj.get("id") else {
            continue;
        };
        if id_val.as_str() != Some(pattern_id) {
            continue;
        }
        let current = obj.get("pinned").and_then(|v| v.as_bool()).unwrap_or(false);
        let next = !current;
        obj.insert("pinned".to_string(), serde_json::Value::Bool(next));
        found = Some(next);
        break;
    }
    if found.is_some() {
        state.version += 1;
        save_state_inner(&state)?;
    }
    Ok(found)
}

fn provider_settings_path() -> PathBuf {
    data_dir().join(PROVIDER_SETTINGS_FILENAME)
}

fn load_provider_runtime_settings() -> ProviderRuntimeSettings {
    let path = provider_settings_path();

    // 1. Primary: clean read+parse wins immediately.
    match fs::read_to_string(&path) {
        Ok(content) => match serde_json::from_str::<ProviderRuntimeSettings>(&content) {
            Ok(settings) => return settings,
            Err(e) => {
                // 2. Corrupt primary: quarantine FIRST so the next save can't
                // copy the corrupt file into .bak and destroy the good backup.
                warn!(
                    "Failed to parse provider settings {:?}: {}, attempting recovery",
                    path, e
                );
                quarantine_corrupt(&path);
            }
        },
        Err(_) => {
            // File-missing: fall through to .bak/.tmp. Genuine first run stays
            // fast and silent → defaults.
        }
    }

    // 3. Backup sibling (.bak). Recovery is read-only (same rationale as
    // load_state): this is reached from unlocked read paths, so we return the
    // recovered value and let the next lock-held save reconcile the primary
    // rather than issuing an unlocked write that could race a writer.
    let backup_path = backup_path_for(&path);
    if let Some(settings) = try_recover::<ProviderRuntimeSettings>(&backup_path) {
        warn!("Recovered provider settings from backup {:?}", backup_path);
        return settings;
    }

    // 4. Orphaned tmp (.tmp).
    let tmp_path = tmp_path_for(&path);
    if let Some(settings) = try_recover::<ProviderRuntimeSettings>(&tmp_path) {
        warn!(
            "Recovered provider settings from orphaned tmp {:?}",
            tmp_path
        );
        return settings;
    }

    // 5. Nothing recoverable → defaults.
    ProviderRuntimeSettings::default()
}

fn save_provider_runtime_settings(settings: &ProviderRuntimeSettings) -> Result<(), String> {
    let dir = ensure_data_dir()?;
    let path = dir.join(PROVIDER_SETTINGS_FILENAME);
    let json = serde_json::to_string_pretty(settings)
        .map_err(|e| format!("Failed to serialize provider settings: {}", e))?;
    write_with_backup(&path, &json)
}

pub fn normalize_ollama_root_base_url(raw: &str) -> Result<String, String> {
    let trimmed = raw.trim();
    if trimmed.is_empty() {
        return Err("Ollama URL cannot be empty.".to_string());
    }

    let mut parsed = reqwest::Url::parse(trimmed)
        .map_err(|_| "Enter a full Ollama URL, for example http://localhost:11434.".to_string())?;
    if !matches!(parsed.scheme(), "http" | "https") {
        return Err("Ollama URL must start with http:// or https://.".to_string());
    }
    if parsed.query().is_some() || parsed.fragment().is_some() {
        return Err("Ollama URL cannot include query parameters or fragments.".to_string());
    }

    let path = parsed.path().trim_end_matches('/');
    let root_path = path
        .strip_suffix("/v1")
        .or_else(|| path.strip_suffix("/api/tags"))
        .unwrap_or(path)
        .to_string();
    parsed.set_path(&root_path);

    Ok(parsed.as_str().trim_end_matches('/').to_string())
}

pub fn load_saved_ollama_base_url() -> Option<String> {
    load_provider_runtime_settings()
        .ollama_base_url
        .and_then(|url| normalize_ollama_root_base_url(&url).ok())
}

pub fn save_ollama_base_url(base_url: Option<String>) -> Result<(), String> {
    let _lock = PROVIDER_SETTINGS_LOCK
        .lock()
        .map_err(|e| format!("Lock poisoned: {}", e))?;
    let mut settings = load_provider_runtime_settings();
    settings.ollama_base_url = base_url;
    save_provider_runtime_settings(&settings)
}

pub fn resolve_ollama_root_base_url() -> String {
    if let Some(saved) = load_saved_ollama_base_url() {
        return saved;
    }

    std::env::var("PACKETADE_OLLAMA_URL")
        .or_else(|_| std::env::var("PACKETCODE_OLLAMA_URL"))
        .ok()
        .and_then(|url| normalize_ollama_root_base_url(&url).ok())
        .unwrap_or_else(|| DEFAULT_OLLAMA_ROOT_BASE_URL.to_string())
}

pub fn resolve_ollama_openai_base_url() -> String {
    format!("{}/v1", resolve_ollama_root_base_url())
}

fn write_with_backup(path: &PathBuf, content: &str) -> Result<(), String> {
    let tmp_path = path.with_extension(format!(
        "{}.tmp",
        path.extension()
            .and_then(|ext| ext.to_str())
            .unwrap_or("json")
    ));
    let backup_path = path.with_extension(format!(
        "{}.bak",
        path.extension()
            .and_then(|ext| ext.to_str())
            .unwrap_or("json")
    ));

    {
        let mut file = fs::File::create(&tmp_path)
            .map_err(|e| format!("Failed to create {:?}: {}", tmp_path, e))?;
        file.write_all(content.as_bytes())
            .map_err(|e| format!("Failed to write {:?}: {}", tmp_path, e))?;
        file.flush()
            .map_err(|e| format!("Failed to flush {:?}: {}", tmp_path, e))?;
        file.sync_all()
            .map_err(|e| format!("Failed to sync {:?}: {}", tmp_path, e))?;
    }

    if path.exists() {
        let previous =
            fs::read(path).map_err(|e| format!("Failed to read existing {:?}: {}", path, e))?;
        fs::write(&backup_path, previous)
            .map_err(|e| format!("Failed to write backup {:?}: {}", backup_path, e))?;
    }

    // Atomically replace the destination. std::fs::rename replaces an existing
    // destination on all platforms (Windows uses MOVEFILE_REPLACE_EXISTING), so
    // we must NOT pre-remove `path` — doing so opens a crash window where
    // neither the primary nor the renamed tmp exists on disk.
    fs::rename(&tmp_path, path).map_err(|e| format!("Failed to replace {:?}: {}", path, e))?;

    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Create a fresh, unique tempdir for one test and return its path.
    /// Mirrors the `std::env::temp_dir()` + nanosecond-suffix convention used
    /// elsewhere in this crate (no extra dev-dependency required).
    fn unique_temp_dir(tag: &str) -> PathBuf {
        let nanos = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .map(|d| d.as_nanos())
            .unwrap_or(0);
        let dir = std::env::temp_dir().join(format!("packetade-storage-{}-{}", tag, nanos));
        fs::create_dir_all(&dir).expect("create unique temp dir");
        dir
    }

    /// Build a recognizable non-default state so we can prove which source the
    /// ladder recovered from. `marker` is encoded both in `version` and in a
    /// single `ServerConfig` name so equality is unambiguous.
    fn marked_state(marker: u32, label: &str) -> PersistedState {
        let mut state = PersistedState::default();
        state.version = marker;
        state.servers = vec![ServerConfig {
            id: format!("srv-{}", marker),
            name: label.to_string(),
            host: "example.test".to_string(),
            port: 2222,
            username: "tester".to_string(),
            auth_method: "agent".to_string(),
            key_path: None,
            remote_path: None,
            last_connected_at: None,
            installed_agents: Vec::new(),
            host_fingerprint: None,
        }];
        state
    }

    fn write_json(path: &Path, state: &PersistedState) {
        let json = serde_json::to_string_pretty(state).expect("serialize marked state");
        fs::write(path, json).expect("write state json");
    }

    /// Assert recovered state matches the marker we encoded (version + server).
    fn assert_marker(state: &PersistedState, marker: u32, label: &str) {
        assert_eq!(state.version, marker, "version marker should match source");
        assert_eq!(
            state.servers.len(),
            1,
            "marker state has exactly one server"
        );
        assert_eq!(
            state.servers[0].name, label,
            "server name marker should match source"
        );
    }

    fn corrupt_file_count(dir: &Path) -> usize {
        fs::read_dir(dir)
            .expect("read temp dir")
            .filter_map(|e| e.ok())
            .filter(|e| {
                e.file_name()
                    .to_str()
                    .map(|n| n.contains(".corrupt-"))
                    .unwrap_or(false)
            })
            .count()
    }

    // 1. Valid primary → loads it.
    #[test]
    fn valid_primary_loads_directly() {
        let dir = unique_temp_dir("valid-primary");
        let primary = dir.join(STATE_FILENAME);
        write_json(&primary, &marked_state(42, "primary-state"));

        let loaded = load_state_from(&dir);
        assert_marker(&loaded, 42, "primary-state");
        assert_eq!(
            corrupt_file_count(&dir),
            0,
            "clean parse must not quarantine"
        );

        let _ = fs::remove_dir_all(&dir);
    }

    // 2. Corrupt primary + good .bak → returns .bak AND primary is quarantined.
    #[test]
    fn corrupt_primary_falls_back_to_bak_and_quarantines() {
        let dir = unique_temp_dir("corrupt-then-bak");
        let primary = dir.join(STATE_FILENAME);
        let bak = backup_path_for(&primary);

        fs::write(&primary, b"{ this is not valid json ::::").expect("write corrupt primary");
        write_json(&bak, &marked_state(77, "bak-state"));

        let loaded = load_state_from(&dir);
        assert_marker(&loaded, 77, "bak-state");

        // The corrupt primary must have been quarantined: a *.corrupt-* file now
        // exists, and the primary path no longer holds the corrupt bytes.
        assert_eq!(
            corrupt_file_count(&dir),
            1,
            "corrupt primary should be quarantined"
        );
        assert!(
            !primary.exists(),
            "primary should have been renamed away by quarantine"
        );

        let _ = fs::remove_dir_all(&dir);
    }

    // 3. Missing primary + good .bak → returns .bak, no quarantine file created.
    #[test]
    fn missing_primary_uses_bak_without_quarantine() {
        let dir = unique_temp_dir("missing-then-bak");
        let primary = dir.join(STATE_FILENAME);
        let bak = backup_path_for(&primary);
        write_json(&bak, &marked_state(88, "bak-only-state"));

        let loaded = load_state_from(&dir);
        assert_marker(&loaded, 88, "bak-only-state");
        assert_eq!(
            corrupt_file_count(&dir),
            0,
            "missing primary must NOT create a quarantine file"
        );

        let _ = fs::remove_dir_all(&dir);
    }

    // 4. Missing primary + missing .bak + good .tmp → returns .tmp.
    #[test]
    fn missing_primary_and_bak_uses_tmp() {
        let dir = unique_temp_dir("missing-then-tmp");
        let primary = dir.join(STATE_FILENAME);
        let tmp = tmp_path_for(&primary);
        write_json(&tmp, &marked_state(99, "tmp-state"));

        let loaded = load_state_from(&dir);
        assert_marker(&loaded, 99, "tmp-state");
        assert_eq!(
            corrupt_file_count(&dir),
            0,
            "no quarantine for missing primary"
        );

        let _ = fs::remove_dir_all(&dir);
    }

    // 5. Corrupt primary + NO .bak + NO .tmp → default AND corrupt file preserved.
    #[test]
    fn corrupt_primary_without_siblings_returns_default_but_preserves_corrupt() {
        let dir = unique_temp_dir("corrupt-no-siblings");
        let primary = dir.join(STATE_FILENAME);
        let corrupt_bytes = b"<<<not json at all>>>";
        fs::write(&primary, corrupt_bytes).expect("write corrupt primary");

        let loaded = load_state_from(&dir);
        // Default state: version 1, no servers — distinct from any marker we set.
        let default = PersistedState::default();
        assert_eq!(loaded.version, default.version, "should be default version");
        assert!(loaded.servers.is_empty(), "default has no servers");

        // Corrupt bytes are preserved under a *.corrupt-* name (not deleted).
        assert_eq!(
            corrupt_file_count(&dir),
            1,
            "corrupt primary must be preserved, not deleted"
        );
        assert!(
            !primary.exists(),
            "primary path no longer holds corrupt bytes"
        );
        // The quarantined file must hold the ORIGINAL corrupt bytes verbatim —
        // "preserved" means recoverable for forensics, not merely renamed-then-emptied.
        let quarantined = fs::read_dir(&dir)
            .expect("read dir")
            .filter_map(|e| e.ok())
            .map(|e| e.path())
            .find(|p| {
                p.file_name()
                    .and_then(|n| n.to_str())
                    .is_some_and(|n| n.contains(".corrupt-"))
            })
            .expect("a quarantine file exists");
        assert_eq!(
            fs::read(&quarantined).expect("read quarantine file"),
            corrupt_bytes,
            "quarantine file must preserve the original corrupt bytes"
        );

        let _ = fs::remove_dir_all(&dir);
    }

    // 6. Genuine first run (nothing on disk) → default, silently (no quarantine).
    #[test]
    fn first_run_returns_default_silently() {
        let dir = unique_temp_dir("first-run");

        let loaded = load_state_from(&dir);
        let default = PersistedState::default();
        assert_eq!(loaded.version, default.version);
        assert!(loaded.servers.is_empty());
        assert!(loaded.flights.is_empty());
        assert_eq!(
            corrupt_file_count(&dir),
            0,
            "first run must not quarantine anything"
        );

        let _ = fs::remove_dir_all(&dir);
    }

    // 7. Durability: after a corrupt-load quarantine, a subsequent
    // write_with_backup(primary, ...) must NOT clobber the still-good .bak.
    // This proves the quarantine-first ordering protects the backup.
    #[test]
    fn quarantine_first_ordering_protects_backup_on_next_write() {
        let dir = unique_temp_dir("durability");
        let primary = dir.join(STATE_FILENAME);
        let bak = backup_path_for(&primary);

        // Good backup on disk; corrupt primary.
        write_json(&bak, &marked_state(123, "protected-bak"));
        fs::write(&primary, b"corrupt!!! not json").expect("write corrupt primary");

        // Load triggers quarantine of the corrupt primary and recovers from .bak.
        let recovered = load_state_from(&dir);
        assert_marker(&recovered, 123, "protected-bak");
        assert!(
            !primary.exists(),
            "primary was quarantined, so it is absent"
        );

        // Now simulate the next lock-held save writing back the recovered state.
        // Because the primary was quarantined (absent), write_with_backup must
        // SKIP the backup-copy step (it only copies when `path.exists()`), so the
        // good .bak survives untouched rather than being overwritten by corrupt
        // primary bytes.
        let json = serde_json::to_string_pretty(&recovered).expect("serialize recovered");
        write_with_backup(&primary, &json).expect("write_with_backup should succeed");

        // Primary now holds the recovered (good) state.
        let primary_after =
            serde_json::from_str::<PersistedState>(&fs::read_to_string(&primary).unwrap())
                .expect("primary should be valid json after save");
        assert_marker(&primary_after, 123, "protected-bak");

        // The .bak must still be the good backup we wrote — never clobbered by
        // the corrupt primary bytes.
        let bak_after = serde_json::from_str::<PersistedState>(&fs::read_to_string(&bak).unwrap())
            .expect("bak should still be valid json (not corrupt bytes)");
        assert_marker(&bak_after, 123, "protected-bak");

        let _ = fs::remove_dir_all(&dir);
    }
}
