use serde::Serialize;
use std::fs;
use std::future::Future;
use std::io::Write;
use std::path::PathBuf;
use std::sync::Mutex;
use tokio::sync::Mutex as AsyncMutex;
use tracing::{info, warn};

use super::agent_config::AgentConfig;
use super::flight::{Flight, Issue, MissionApprovalRequest};
use super::orchestrator::OrchestratorSettings;
use super::shared::home_dir;
use super::workspace::Workspace;

/// A post-flight retrospective capturing what worked, what failed, and lessons learned.
/// Generated by AI after a flight completes, used to improve future flight planning.
#[derive(Debug, Clone, Serialize, serde::Deserialize)]
pub struct FlightRetrospective {
    pub id: String,
    pub flight_id: String,
    pub flight_title: String,
    pub summary: String,
    #[serde(default)]
    pub what_worked: Vec<String>,
    #[serde(default)]
    pub what_failed: Vec<String>,
    #[serde(default)]
    pub lessons_learned: Vec<String>,
    #[serde(default)]
    pub suggested_improvements: Vec<String>,
    #[serde(default)]
    pub tags: Vec<String>,
    pub created_at: u64,
}

/// A saved SSH server connection configuration.
#[derive(Debug, Clone, Serialize, serde::Deserialize)]
pub struct ServerConfig {
    pub id: String,
    pub name: String,
    pub host: String,
    #[serde(default = "default_ssh_port")]
    pub port: u16,
    pub username: String,
    pub auth_method: String, // "agent" | "key" | "password"
    #[serde(default)]
    pub key_path: Option<String>,
    #[serde(default)]
    pub remote_path: Option<String>,
    #[serde(default)]
    pub last_connected_at: Option<u64>,
    #[serde(default)]
    pub installed_agents: Vec<String>,
    /// SHA256 fingerprint of the host key captured at first-connect.
    /// `None` for legacy entries — those connect via TOFU fallback until
    /// the user re-saves the server to pin the key.
    #[serde(default)]
    pub host_fingerprint: Option<String>,
}

fn default_ssh_port() -> u16 {
    22
}

pub const STATE_FILENAME: &str = "state.v1.json";
const PROVIDER_SETTINGS_FILENAME: &str = "provider-settings.v1.json";
pub const DEFAULT_OLLAMA_ROOT_BASE_URL: &str = "http://localhost:11434";

static STATE_LOCK: Mutex<()> = Mutex::new(());
static PROVIDER_SETTINGS_LOCK: Mutex<()> = Mutex::new(());

/// Async-safe critical-section mutex for `with_state_lock` callers. Held
/// across the **entire** load → mutate → save sequence so concurrent async
/// writers can't lose each other's mutations. Distinct from `STATE_LOCK`
/// (which is a sync mutex that only protects the write itself and would
/// be illegal to hold across an `.await`).
///
/// Migration note: callers that take `&mut PersistedState` and only need
/// to be serialized against other planner-tool callers should use
/// [`with_state_lock`]. The orchestrator's existing sync helper
/// (`commands::orchestration::with_orchestrator_and_flights`) is **not**
/// gated on this mutex — it holds the sync `Orchestrator` mutex across
/// its load-mutate-save, which serializes its own writers but can still
/// theoretically race against the async path. Tightening that bridge is
/// tracked in the backlog (see "Mission Planner v1.1" P3 entries).
static ASYNC_STATE_LOCK: AsyncMutex<()> = AsyncMutex::const_new(());

#[derive(Debug, Clone, Serialize, serde::Deserialize, Default)]
struct ProviderRuntimeSettings {
    #[serde(default)]
    ollama_base_url: Option<String>,
}

#[derive(Debug, Clone, Serialize, serde::Deserialize, Default)]
pub struct PersistedUiState {
    pub selected_flight_id: Option<String>,
    pub selected_view: Option<String>,
    pub theme: Option<String>,
}

#[derive(Debug, Clone, Serialize, serde::Deserialize)]
pub struct PersistedState {
    pub version: u32,
    pub flights: Vec<Flight>,
    pub agents: Vec<AgentConfig>,
    pub settings: OrchestratorSettings,
    pub ui: PersistedUiState,
    #[serde(default)]
    pub issues: Vec<Issue>,
    #[serde(default)]
    pub workspaces: Vec<Workspace>,
    #[serde(default)]
    pub retrospectives: Vec<FlightRetrospective>,
    #[serde(default)]
    pub memory_events: Vec<serde_json::Value>,
    #[serde(default)]
    pub memory_patterns: Vec<serde_json::Value>,
    #[serde(default)]
    pub servers: Vec<ServerConfig>,
    /// Mission Planner: pending / resolved `request_user_approval`
    /// records. Filed async-style by the planner via the MCP tool
    /// surface (E2) and drained by `resolve_mission_approval`.
    #[serde(default)]
    pub mission_approvals: Vec<MissionApprovalRequest>,
}

impl Default for PersistedState {
    fn default() -> Self {
        Self {
            version: 1,
            flights: Vec::new(),
            agents: Vec::new(),
            settings: OrchestratorSettings::default(),
            ui: PersistedUiState::default(),
            issues: Vec::new(),
            workspaces: Vec::new(),
            retrospectives: Vec::new(),
            memory_events: Vec::new(),
            memory_patterns: Vec::new(),
            servers: Vec::new(),
            mission_approvals: Vec::new(),
        }
    }
}

/// Get the PacketADE data directory (~/.packetade/)
pub fn data_dir() -> PathBuf {
    let home = home_dir().unwrap_or_else(|| ".".to_string());
    PathBuf::from(home).join(crate::core::brand::DATA_DIR_NAME)
}

/// Ensure the data directory exists.
pub fn ensure_data_dir() -> Result<PathBuf, String> {
    let dir = data_dir();
    if !dir.exists() {
        fs::create_dir_all(&dir)
            .map_err(|e| format!("Failed to create data dir {:?}: {}", dir, e))?;
        info!(
            "Created {} data dir: {:?}",
            crate::core::brand::APP_NAME,
            dir
        );
    }
    Ok(dir)
}

pub fn load_state() -> PersistedState {
    let path = data_dir().join(STATE_FILENAME);
    match fs::read_to_string(&path) {
        Ok(content) => match serde_json::from_str::<PersistedState>(&content) {
            Ok(state) => state,
            Err(e) => {
                warn!("Failed to parse {:?}: {}, using default state", path, e);
                PersistedState::default()
            }
        },
        Err(_) => PersistedState::default(),
    }
}

fn save_state_inner(state: &PersistedState) -> Result<(), String> {
    let dir = ensure_data_dir()?;
    let path = dir.join(STATE_FILENAME);
    let json = serde_json::to_string_pretty(state)
        .map_err(|e| format!("Failed to serialize persisted state: {}", e))?;
    write_with_backup(&path, &json)?;
    Ok(())
}

pub fn save_state(state: &PersistedState) -> Result<(), String> {
    let _lock = STATE_LOCK
        .lock()
        .map_err(|e| format!("Lock poisoned: {}", e))?;
    let mut state = state.clone();
    state.version += 1;
    save_state_inner(&state)
}

/// Atomic load → mutate → save under `STATE_LOCK`. Mirrors the slice-writer
/// pattern (e.g. `save_flights`) for callers that need to merge multiple
/// fields into the persisted state in a single critical section, instead of
/// `load_state(); mutate; save_state()` — which exposes a lost-update race
/// against concurrent slice writers landing between the load and the save.
pub fn update_state<F, R>(mutate: F) -> Result<R, String>
where
    F: FnOnce(&mut PersistedState) -> R,
{
    let _lock = STATE_LOCK
        .lock()
        .map_err(|e| format!("Lock poisoned: {}", e))?;
    let mut state = load_state();
    let result = mutate(&mut state);
    state.version += 1;
    save_state_inner(&state)?;
    Ok(result)
}

/// Run an async closure with an exclusive load → mutate → save critical
/// section over `PersistedState`. Solves the lost-update race that
/// `load_state(); mutate; save_state()` exposes when called from
/// concurrent async contexts (e.g. multiple Mission Planner MCP tool
/// handlers firing in parallel within a single planner turn).
///
/// Contract:
///   * The closure receives a `&mut PersistedState` already loaded under
///     the mutex.
///   * If the closure returns `Ok(R)`, the state is persisted under the
///     same lock and `R` is returned to the caller.
///   * If the closure returns `Err`, the state is **not** persisted — the
///     mutex is released and the error is propagated unchanged.
///   * The mutex is held across the closure's `.await` points, so callers
///     MUST NOT re-enter `with_state_lock` from within their closure
///     (doing so will deadlock).
///   * Tokio `Mutex` is fair-ish and not cancellation-safe at the lock
///     acquire site — callers that need to abort should drop the future
///     *before* it acquires the lock.
///
/// Anything currently using `save_state` directly is left alone — only the
/// load-mutate-save composite (where the race exists) needs this helper.
pub async fn with_state_lock<F, Fut, R>(action: F) -> Result<R, String>
where
    F: FnOnce(&mut PersistedState) -> Fut,
    Fut: Future<Output = Result<R, String>>,
{
    let _guard = ASYNC_STATE_LOCK.lock().await;
    let mut state = load_state();
    let result = action(&mut state).await?;
    save_state(&state)?;
    Ok(result)
}

pub fn save_flights(flights: Vec<Flight>) -> Result<(), String> {
    let _lock = STATE_LOCK
        .lock()
        .map_err(|e| format!("Lock poisoned: {}", e))?;
    let mut state = load_state();
    state.flights = flights;
    state.version += 1;
    save_state_inner(&state)
}

pub fn save_agents(agents: Vec<AgentConfig>) -> Result<(), String> {
    let _lock = STATE_LOCK
        .lock()
        .map_err(|e| format!("Lock poisoned: {}", e))?;
    let mut state = load_state();
    state.agents = agents;
    state.version += 1;
    save_state_inner(&state)
}

pub fn save_settings(settings: OrchestratorSettings) -> Result<(), String> {
    let _lock = STATE_LOCK
        .lock()
        .map_err(|e| format!("Lock poisoned: {}", e))?;
    let mut state = load_state();
    state.settings = settings;
    state.version += 1;
    save_state_inner(&state)
}

pub fn save_ui(ui: PersistedUiState) -> Result<(), String> {
    let _lock = STATE_LOCK
        .lock()
        .map_err(|e| format!("Lock poisoned: {}", e))?;
    let mut state = load_state();
    state.ui = ui;
    state.version += 1;
    save_state_inner(&state)
}

pub fn save_issues(issues: Vec<Issue>) -> Result<(), String> {
    let _lock = STATE_LOCK
        .lock()
        .map_err(|e| format!("Lock poisoned: {}", e))?;
    let mut state = load_state();
    state.issues = issues;
    state.version += 1;
    save_state_inner(&state)
}

pub fn save_workspaces(workspaces: Vec<Workspace>) -> Result<(), String> {
    let _lock = STATE_LOCK
        .lock()
        .map_err(|e| format!("Lock poisoned: {}", e))?;
    let mut state = load_state();
    state.workspaces = workspaces;
    state.version += 1;
    save_state_inner(&state)
}

pub fn save_servers(servers: Vec<ServerConfig>) -> Result<(), String> {
    let _lock = STATE_LOCK
        .lock()
        .map_err(|e| format!("Lock poisoned: {}", e))?;
    let mut state = load_state();
    state.servers = servers;
    state.version += 1;
    save_state_inner(&state)
}

pub fn save_memory(
    events: Vec<serde_json::Value>,
    patterns: Vec<serde_json::Value>,
) -> Result<(), String> {
    let _lock = STATE_LOCK
        .lock()
        .map_err(|e| format!("Lock poisoned: {}", e))?;
    let mut state = load_state();
    state.memory_events = events;
    state.memory_patterns = patterns;
    state.version += 1;
    save_state_inner(&state)
}

/// v0.8-H: atomically flip the `pinned` flag on a single LearnedPattern by id.
/// Returns the new `pinned` value (or `None` if the pattern was not found).
/// Storing as `serde_json::Value` lets us mutate the field in-place rather
/// than round-tripping the whole slice — robust across schema additions.
pub fn toggle_pinned_pattern(pattern_id: &str) -> Result<Option<bool>, String> {
    let _lock = STATE_LOCK
        .lock()
        .map_err(|e| format!("Lock poisoned: {}", e))?;
    let mut state = load_state();
    let mut found: Option<bool> = None;
    for entry in state.memory_patterns.iter_mut() {
        let Some(obj) = entry.as_object_mut() else {
            continue;
        };
        let Some(id_val) = obj.get("id") else { continue };
        if id_val.as_str() != Some(pattern_id) {
            continue;
        }
        let current = obj
            .get("pinned")
            .and_then(|v| v.as_bool())
            .unwrap_or(false);
        let next = !current;
        obj.insert("pinned".to_string(), serde_json::Value::Bool(next));
        found = Some(next);
        break;
    }
    if found.is_some() {
        state.version += 1;
        save_state_inner(&state)?;
    }
    Ok(found)
}

fn provider_settings_path() -> PathBuf {
    data_dir().join(PROVIDER_SETTINGS_FILENAME)
}

fn load_provider_runtime_settings() -> ProviderRuntimeSettings {
    let path = provider_settings_path();
    match fs::read_to_string(&path) {
        Ok(content) => match serde_json::from_str::<ProviderRuntimeSettings>(&content) {
            Ok(settings) => settings,
            Err(e) => {
                warn!(
                    "Failed to parse provider settings {:?}: {}, using defaults",
                    path, e
                );
                ProviderRuntimeSettings::default()
            }
        },
        Err(_) => ProviderRuntimeSettings::default(),
    }
}

fn save_provider_runtime_settings(settings: &ProviderRuntimeSettings) -> Result<(), String> {
    let dir = ensure_data_dir()?;
    let path = dir.join(PROVIDER_SETTINGS_FILENAME);
    let json = serde_json::to_string_pretty(settings)
        .map_err(|e| format!("Failed to serialize provider settings: {}", e))?;
    write_with_backup(&path, &json)
}

pub fn normalize_ollama_root_base_url(raw: &str) -> Result<String, String> {
    let trimmed = raw.trim();
    if trimmed.is_empty() {
        return Err("Ollama URL cannot be empty.".to_string());
    }

    let mut parsed = reqwest::Url::parse(trimmed)
        .map_err(|_| "Enter a full Ollama URL, for example http://localhost:11434.".to_string())?;
    if !matches!(parsed.scheme(), "http" | "https") {
        return Err("Ollama URL must start with http:// or https://.".to_string());
    }
    if parsed.query().is_some() || parsed.fragment().is_some() {
        return Err("Ollama URL cannot include query parameters or fragments.".to_string());
    }

    let path = parsed.path().trim_end_matches('/');
    let root_path = path
        .strip_suffix("/v1")
        .or_else(|| path.strip_suffix("/api/tags"))
        .unwrap_or(path)
        .to_string();
    parsed.set_path(&root_path);

    Ok(parsed.as_str().trim_end_matches('/').to_string())
}

pub fn load_saved_ollama_base_url() -> Option<String> {
    load_provider_runtime_settings()
        .ollama_base_url
        .and_then(|url| normalize_ollama_root_base_url(&url).ok())
}

pub fn save_ollama_base_url(base_url: Option<String>) -> Result<(), String> {
    let _lock = PROVIDER_SETTINGS_LOCK
        .lock()
        .map_err(|e| format!("Lock poisoned: {}", e))?;
    let mut settings = load_provider_runtime_settings();
    settings.ollama_base_url = base_url;
    save_provider_runtime_settings(&settings)
}

pub fn resolve_ollama_root_base_url() -> String {
    if let Some(saved) = load_saved_ollama_base_url() {
        return saved;
    }

    std::env::var("PACKETADE_OLLAMA_URL")
        .or_else(|_| std::env::var("PACKETCODE_OLLAMA_URL"))
        .ok()
        .and_then(|url| normalize_ollama_root_base_url(&url).ok())
        .unwrap_or_else(|| DEFAULT_OLLAMA_ROOT_BASE_URL.to_string())
}

pub fn resolve_ollama_openai_base_url() -> String {
    format!("{}/v1", resolve_ollama_root_base_url())
}

fn write_with_backup(path: &PathBuf, content: &str) -> Result<(), String> {
    let tmp_path = path.with_extension(format!(
        "{}.tmp",
        path.extension()
            .and_then(|ext| ext.to_str())
            .unwrap_or("json")
    ));
    let backup_path = path.with_extension(format!(
        "{}.bak",
        path.extension()
            .and_then(|ext| ext.to_str())
            .unwrap_or("json")
    ));

    {
        let mut file = fs::File::create(&tmp_path)
            .map_err(|e| format!("Failed to create {:?}: {}", tmp_path, e))?;
        file.write_all(content.as_bytes())
            .map_err(|e| format!("Failed to write {:?}: {}", tmp_path, e))?;
        file.flush()
            .map_err(|e| format!("Failed to flush {:?}: {}", tmp_path, e))?;
        file.sync_all()
            .map_err(|e| format!("Failed to sync {:?}: {}", tmp_path, e))?;
    }

    if path.exists() {
        let previous =
            fs::read(path).map_err(|e| format!("Failed to read existing {:?}: {}", path, e))?;
        fs::write(&backup_path, previous)
            .map_err(|e| format!("Failed to write backup {:?}: {}", backup_path, e))?;
    }

    if path.exists() {
        fs::remove_file(path).map_err(|e| format!("Failed to replace {:?}: {}", path, e))?;
    }

    fs::rename(&tmp_path, path).map_err(|e| format!("Failed to replace {:?}: {}", path, e))?;

    Ok(())
}
