import { describe, expect, it } from "vitest";
import { render, screen } from "@testing-library/react";
import {
  extent,
  linePath,
  linearScale,
  niceUpperBound,
  sampleIndices,
  tickStep,
  ticks,
} from "./scale";
import { rampIndex } from "./tokens";
import { TimeSeriesChart } from "./TimeSeriesChart";
import { HeatmapGrid } from "./HeatmapGrid";
import { BarSeries } from "./BarSeries";

/**
 * Two claims are under test here, because both underwrite the decision
 * recorded in `dev/dictation-analytics-charting.md`:
 *
 * 1. The hand-rolled maths reproduces d3 exactly. Every expected value below
 *    was generated by running the real `d3-shape` / `d3-array` / `d3-scale`
 *    packages, not by reading this implementation back to itself.
 * 2. The degenerate inputs render. Empty and single-datapoint series are where
 *    hand-rolled charts break, and where the vibe2text originals silently
 *    render nothing.
 */

describe("scale — parity with d3", () => {
  it("reproduces d3.curveMonotoneX for a typical series", () => {
    const points = [
      { x: 0, y: 80 },
      { x: 25, y: 20 },
      { x: 50, y: 60 },
      { x: 75, y: 10 },
      { x: 100, y: 45 },
    ];
    // From d3-shape 3.2.0: line().curve(curveMonotoneX), rounded to 2dp.
    expect(linePath(points, "monotone")).toBe(
      "M0,80C8.33,50,16.67,20,25,20C33.33,20,41.67,60,50,60C58.33,60,66.67,10,75,10C83.33,10,91.67,27.5,100,45",
    );
  });

  it("reproduces d3.curveMonotoneX across a plateau", () => {
    // Flat runs are where a naive Fritsch-Carlson port overshoots.
    const points = [
      { x: 0, y: 50 },
      { x: 10, y: 50 },
      { x: 20, y: 50 },
      { x: 30, y: 10 },
    ];
    expect(linePath(points, "monotone")).toBe(
      "M0,50C3.33,50,6.67,50,10,50C13.33,50,16.67,50,20,50C23.33,50,26.67,30,30,10",
    );
  });

  it("reproduces d3.ticks, including the sub-unit float boundary", () => {
    // 0.35 / 0.05 evaluates to 6.999999999999999; a naive Math.floor drops it.
    expect(ticks(0, 0.35, 5)).toEqual([0, 0.05, 0.1, 0.15, 0.2, 0.25, 0.3, 0.35]);
    expect(ticks(0, 4180, 3)).toEqual([0, 1000, 2000, 3000, 4000]);
    expect(ticks(-1, 1, 4)).toEqual([-1, -0.5, 0, 0.5, 1]);
    expect(tickStep(0, 4180, 4)).toBe(1000);
  });

  it("maps values like d3.scaleLinear", () => {
    expect(linearScale([0, 10], [0, 100])(2.5)).toBe(25);
  });
});

describe("scale — degenerate inputs", () => {
  it("centres a zero-width domain instead of dividing by zero", () => {
    const scale = linearScale([5, 5], [0, 100]);
    expect(scale(5)).toBe(50);
    expect(Number.isNaN(scale(99))).toBe(false);
  });

  it("returns null extent for an empty or all-NaN series", () => {
    expect(extent([])).toBeNull();
    expect(extent([Number.NaN])).toBeNull();
    expect(extent([3, Number.NaN, 1])).toEqual([1, 3]);
  });

  it("emits a bare move for one point and nothing for none", () => {
    expect(linePath([])).toBe("");
    expect(linePath([{ x: 1, y: 2 }])).toBe("M1,2");
  });

  it("rounds the value axis to a tick boundary", () => {
    // The vibe2text renderers use max * 1.1, which lands the axis on 4598.
    expect(niceUpperBound(4180)).toBe(5000);
    expect(niceUpperBound(0)).toBe(1);
  });

  it("samples axis label indices without duplicates", () => {
    expect(sampleIndices(0, 5)).toEqual([]);
    expect(sampleIndices(1, 5)).toEqual([0]);
    expect(sampleIndices(2, 5)).toEqual([0, 1]);
    expect(sampleIndices(30, 5)).toEqual([0, 7, 15, 22, 29]);
  });

  it("keeps zero visually distinct from the smallest non-zero value", () => {
    expect(rampIndex(0, 10)).toBe(0);
    expect(rampIndex(1, 10)).toBe(1);
    expect(rampIndex(10, 10)).toBe(4);
    expect(rampIndex(5, 0)).toBe(1);
  });
});

describe("TimeSeriesChart", () => {
  it("renders the empty state rather than a blank panel", () => {
    render(<TimeSeriesChart title="Words per day" data={[]} />);
    expect(screen.getByText("No data yet")).toBeInTheDocument();
  });

  it("renders a single datapoint without producing NaN geometry", () => {
    const { container } = render(
      <TimeSeriesChart
        title="Words per day"
        data={[{ date: "2026-08-20", value: 412 }]}
        unit="words"
      />,
    );
    expect(container.innerHTML).not.toContain("NaN");
    // One point draws a dot; there is no line to stroke.
    expect(container.querySelectorAll("circle")).toHaveLength(1);
    expect(container.querySelectorAll("path")).toHaveLength(0);
  });

  it("draws a stroked path and a data table for a real series", () => {
    render(
      <TimeSeriesChart
        title="Words per day"
        data={[
          { date: "2026-08-20", value: 412 },
          { date: "2026-08-21", value: 980 },
          { date: "2026-08-22", value: 260 },
        ]}
        unit="words"
      />,
    );
    expect(screen.getByRole("group", { name: /Words per day/ })).toBeInTheDocument();
    expect(screen.getByText("Show data table")).toBeInTheDocument();
    expect(screen.getAllByRole("row")).toHaveLength(4); // header + 3
  });

  it("survives an all-equal series", () => {
    const { container } = render(
      <TimeSeriesChart
        title="Flat"
        data={[
          { date: "2026-08-20", value: 7 },
          { date: "2026-08-21", value: 7 },
          { date: "2026-08-22", value: 7 },
        ]}
      />,
    );
    expect(container.innerHTML).not.toContain("NaN");
  });

  it("names itself for assistive technology", () => {
    render(
      <TimeSeriesChart
        title="WPM"
        data={[
          { date: "2026-08-20", value: 120 },
          { date: "2026-08-21", value: 150 },
        ]}
        unit="wpm"
      />,
    );
    const figure = screen.getByRole("group", { name: /WPM: 2 readings/ });
    expect(figure).toBeInTheDocument();
  });
});

describe("HeatmapGrid", () => {
  it("treats an all-zero matrix as empty", () => {
    render(
      <HeatmapGrid
        title="Activity"
        rows={Array.from({ length: 7 }, () => new Array<number>(24).fill(0))}
        rowLabels={["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"]}
      />,
    );
    expect(screen.getByText("No activity recorded yet")).toBeInTheDocument();
  });

  it("renders every cell and reports the busiest slot", () => {
    const rows = Array.from({ length: 7 }, () => new Array<number>(24).fill(0));
    rows[2][14] = 9;
    rows[3][9] = 4;
    const { container } = render(
      <HeatmapGrid
        title="Activity"
        rows={rows}
        rowLabels={["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"]}
        unit="transcriptions"
        cellLabel={(r, c) =>
          `${["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"][r]} ${String(c).padStart(2, "0")}:00`
        }
      />,
    );
    expect(container.querySelectorAll("[title]")).toHaveLength(7 * 24);
    expect(
      screen.getByRole("group", { name: /Busiest is Tue 14:00 — 9 transcriptions/ }),
    ).toBeInTheDocument();
  });

  it("tolerates ragged rows", () => {
    const { container } = render(
      <HeatmapGrid title="Ragged" rows={[[1, 2, 3], [4]]} rowLabels={["A", "B"]} />,
    );
    expect(container.innerHTML).not.toContain("NaN");
    expect(container.innerHTML).not.toContain("undefined");
  });
});

describe("BarSeries", () => {
  it("renders the empty state when every value is null", () => {
    render(
      <BarSeries
        title="WPM by hour"
        data={Array.from({ length: 24 }, (_unused, hour) => ({
          label: `${hour}:00`,
          value: null,
        }))}
      />,
    );
    expect(screen.getByText("No data yet")).toBeInTheDocument();
  });

  it("does not divide by zero when every value is zero", () => {
    const { container } = render(
      <BarSeries
        title="Fillers"
        orientation="horizontal"
        data={[
          { label: "um", value: 0 },
          { label: "like", value: 0 },
        ]}
      />,
    );
    expect(container.innerHTML).not.toContain("NaN");
  });

  it("keeps null slots visually distinct from zero readings", () => {
    const { container } = render(
      <BarSeries
        title="WPM by hour"
        data={[
          { label: "0:00", value: null },
          { label: "1:00", value: 0 },
          { label: "2:00", value: 140 },
        ]}
        unit="wpm"
      />,
    );
    expect(container.querySelector('[title="0:00 — no reading"]')).not.toBeNull();
    expect(container.querySelector('[title="1:00 — 0 wpm"]')).not.toBeNull();
  });

  it("honours a shared ceiling so sibling panels stay comparable", () => {
    const { container } = render(
      <BarSeries
        title="This week"
        orientation="horizontal"
        data={[{ label: "Words", value: 500 }]}
        maxValue={1000}
      />,
    );
    expect(container.innerHTML).toContain("width: 50%");
  });
});
